name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: |
          npm i -g corepack@latest
          corepack enable pnpm
      - run: pnpm i
      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm build
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: |
          npm i -g corepack@latest
          corepack enable pnpm
      - run: pnpm i
      - run: pnpm playwright install --with-deps chromium
      - run: pnpm build
      - run: |
          ATPROTO_SHA=$(< .atproto-sha)
          echo "ATPROTO_SHA=$ATPROTO_SHA" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: /home/runner/.cache/pdsadmin-web
          key: atproto-${{ env.ATPROTO_SHA }}
      - run: pnpm setup-dev-env
      - run: pnpm e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
